# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "akthmd-portfolio-platform-terraform-backend-states"
    dynamodb_table = "akthmd-portfolio-platform-terraform-backend-locks"
    encrypt        = true
    key            = "live/oci-staging/terraform.tfstate"
    profile        = "personal-local-dev"
    region         = "ap-south-1"
  }
}
