# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    oci = {
      source  = "oracle/oci"
      version = "~> 5.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.20"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.10"
    }
  }
}

provider "oci" {
  tenancy_ocid     = "ocid1.tenancy.oc1..aaaaaaaawnzgt5r5hjvtrsu5l46o7itbujheahdws3a4apfqxsj4bl3omikq"
  user_ocid        = "ocid1.user.oc1..aaaaaaaal4ddpa2cwdjuudehjps2ebbnjdwint2i53mxixavob5cew6lp4ka"
  fingerprint      = "d5:e6:6a:8f:06:7c:e7:0a:53:62:b2:25:36:27:c5:25"
  private_key_path = "/home/vscode/.oci/oci_api_key_nopass.pem"
  region           = "il-jerusalem-1"
}
